---
name: Check release PR labels

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - edited
      - synchronize
      - ready_for_review
      - converted_to_draft
      - locked
      - unlocked
    branches:
      - main

jobs:
  check-pr-label-and-comment:
    runs-on: ubuntu-latest

    steps:
      - uses: yashhy/pr-label-check-and-comment-action@master
        with:
          required_labels: 'release:patch, release:minor, release:major, norelease'
          GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN}}'
