---
name: Build and publish docker image

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize
  push:
    branches:
      - main

jobs:
  publish-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Generate image name
        id: image-name
        run: |
          PACKAGE_VERSION=$(cat ./package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
          PACKAGE_NAME=$(cat ./package.json | grep name | head -1 | awk -F: '{ print $2 }' | awk -F/ '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]'#*@)
          echo "::set-output name=image_name::openmailarchive/${PACKAGE_NAME}:${PACKAGE_VERSION}"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{steps.image-name.outputs.image_name}}
