---
name: Publish package

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'Release')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Make sure the code is in good shape
        run: npm run format && npm run lint

      - name: Build the project
        run: npm run build

      - name: Publish package on NPM 📦
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
