---
name: Publish a prerelease package

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize

jobs:
  publish-prerelease:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install dependencies
        run: npm install

      - name: Bump prerelease version
        run: npm version prerelease --no-git-tag-version

      - name: Commit new version
        uses: EndBug/add-and-commit@v9
        with:
          push: true
          author_name: Github Action
          committer_name: Github Action
