---
name: Publish a prerelease package

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize

jobs:
  publish-prerelease:
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'dev:prerelease')

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Make sure the code is in good shape
        run: npm run format && npm run lint

      - name: Bump prerelease version
        run: npm version prerelease --no-git-tag-version

      - name: Commit new version
        uses: EndBug/add-and-commit@v9
        with:
          push: true
          author_name: Github Action
          committer_name: Github Action

      - name: Build the project
        run: npm run build

      - name: Publish package on NPM 📦
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
